/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra241_2015_pnrs1_rtrk_taskmanager_StatistikaNative */

#ifndef _Included_ra241_2015_pnrs1_rtrk_taskmanager_StatistikaNative
#define _Included_ra241_2015_pnrs1_rtrk_taskmanager_StatistikaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra241_2015_pnrs1_rtrk_taskmanager_StatistikaNative
 * Method:    izracunajStatistiku
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ra241_12015_pnrs1_rtrk_taskmanager_StatistikaNative_izracunajStatistiku
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
